const $=s=>document.querySelector(s);
const question=$("#question"), result=$("#result"), solveBtn=$("#solveBtn"), imageInput=$("#imageInput"), preview=$("#imagePreview");
const demoSolve=(q)=>{const x=q.toLowerCase(); if(x.includes("2x")&&x.includes("17")) return {answer:"x = 6",steps:["Start with 2x + 5 = 17.","Subtract 5 from both sides: 2x = 12.","Divide both sides by 2: x = 6."],explain:"We undo the operations around x in reverse order: first subtraction, then division.",verify:"2(6) + 5 = 17 ✓"}; if(x.match(/^\s*\d+\s*[\+\-\*x×÷\/]\s*\d+/)){try{let expr=q.replace(/×/g,"*").replace(/÷/g,"/").replace(/[^0-9+*/(). -]/g,""); let v=Function("return "+expr)(); return {answer:String(v),steps:["Rewrite the expression using standard arithmetic symbols.","Apply multiplication/division before addition/subtraction.","Calculate the remaining operation."],explain:"The standard order of operations keeps the calculation consistent.",verify:"Recalculation confirms the result ✓"}}catch(e){} } return {answer:"AI endpoint ready",steps:["Your frontend is connected to the solver interface.","For production, send this question to /api/solve.","The backend should return structured steps, explanation, and verification."],explain:"This demo keeps secret AI credentials out of the browser. Connect your secure server-side AI provider to /api/solve.",verify:"Backend verification will appear here when configured."}};
solveBtn.onclick=async()=>{const q=question.value.trim(); if(!q){question.focus();return} solveBtn.disabled=true; solveBtn.innerHTML="Solving…"; result.classList.remove("hidden"); result.innerHTML="<strong>Thinking through the problem…</strong>"; try{const r=await fetch("/api/solve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,class:$("#classSelect").value,topic:$("#topicSelect").value,language:$("#lang").value})}); if(r.ok){const d=await r.json(); renderResult(d)} else throw Error()}catch(e){renderResult(demoSolve(q))} finally{solveBtn.disabled=false;solveBtn.innerHTML="Solve with AI <span>→</span>"}};
function renderResult(d){result.innerHTML=`<h4>Final Answer</h4><div class="answer">${d.answer||"—"}</div><h4>Step-by-Step Solution</h4><ol>${(d.steps||[]).map(s=>`<li>${s}</li>`).join("")}</ol><h4>Easy Explanation</h4><p>${d.explanation||d.explain||"See the steps above."}</p><h4>Verification</h4><p>${d.verification||d.verify||"Verification unavailable."}</p>`}
imageInput.onchange=()=>{const f=imageInput.files[0];if(!f)return;preview.classList.remove("hidden");preview.innerHTML=`<img alt="Question preview" src="${URL.createObjectURL(f)}">`;question.placeholder="Add any instructions for this image…"};
$("#cameraBtn").onclick=()=>{const input=document.createElement("input");input.type="file";input.accept="image/*";input.capture="environment";input.onchange=()=>{imageInput.files=input.files;imageInput.dispatchEvent(new Event("change"))};input.click()};
$("#voiceBtn").onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Voice input is not supported by this browser.");return}const r=new SR();r.lang=$("#lang").value==="ur"?"ur-PK":$("#lang").value==="ps"?"ps-AF":"en-US";r.onresult=e=>question.value=e.results[0][0].transcript;r.start()};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.theme=document.body.classList.contains("dark")?"dark":"light"};
if(localStorage.theme==="dark")document.body.classList.add("dark");
$("#practiceBtn").onclick=()=>alert("Practice generation is ready to connect to your secure practice API.");
$("#lang").onchange=()=>{const l=$("#lang").value;document.documentElement.lang=l; if(l==="ur"){question.placeholder="اپنا ریاضی کا سوال یہاں لکھیں…";}else if(l==="ps"){question.placeholder="خپل د ریاضۍ پوښتنه دلته ولیکئ…";}else question.placeholder="Type your maths question here…"};
